name : Ibsciss.org
brand : Ibsciss.org
description :
keyword:
url : /
imageurl: http://www.daigo.org/wordpress/wp-content/themes/daigo_org-theme-2013/img/glasses.png
email : alemaire@quantis.fr
twitter : lilobase
github : ibsciss
author: ibsciss.org
analytics:
year: 2014
markdown: kramdown
exclude: [scss, node_modules]